[package]
name = "protocol-dubbo2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remoting-base.workspace = true
protocol-base.workspace = true
