[package]
name = "protocol-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap.workspace = true
dubbo-base.workspace = true
thiserror.workspace = true